version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
  rabbitmq:
    image: "rabbitmq:3.7.12-alpine"
    expose:
      - "5672"