# Generated by Django 2.2.3 on 2020-04-19 03:38

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='photos/profiles/default.png', max_length=200, upload_to=accounts.models.get_filename_profile)),
                ('str_id', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('mobile', models.IntegerField()),
                ('is_mobile_verified', models.NullBooleanField(default=None)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.SmallIntegerField(default=1, help_text='Set to 1 for this collection to be the first, 2 to be second etc.')),
                ('big_field', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight', models.FloatField(null=True)),
                ('facebook_url', models.URLField(max_length=255)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
